---
- name: Create app directory
  file:
    path: /opt/vaultwarden
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Copy docker-compose.yml
  template:
    src: docker-compose.yml.j2
    dest: /opt/vaultwarden/docker-compose.yml
    owner: root
    group: root
    mode: '0644'

- name: Start Vaultwarden
  shell: docker compose up -d
  args:
    chdir: /opt/vaultwarden
