---
- name: Create Traefik directory
  file:
    path: /opt/traefik
    state: directory
    mode: '0755'

- name: Create external proxy network
  docker_network:
    name: proxy
    state: present

- name: Deploy Traefik static configuration
  template:
    src: traefik.yml.j2
    dest: /opt/traefik/traefik.yml
    mode: '0644'

- name: Create acme.json file
  file:
    path: /opt/traefik/acme.json
    state: touch
    mode: '0600'

- name: Deploy Traefik docker-compose
  template:
    src: docker-compose.yml.j2
    dest: /opt/traefik/docker-compose.yml
    mode: '0644'

- name: Launch Traefik
  shell: docker compose up -d
  args:
    chdir: /opt/traefik
