---
- name: Create grafana directory
  file:
    path: /opt/grafana
    state: directory
    mode: '0755'

- name: Deploy docker-compose.yml
  template:
    src: docker-compose.yml.j2
    dest: /opt/grafana/docker-compose.yml
    mode: '0644'

- name: Launch Grafana
  shell: docker compose up -d
  args:
    chdir: /opt/grafana
