- name: Cr√©er le dossier de la stack NPM
  file:
    path: /opt/npm
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Copier le docker-compose.yml
  copy:
    src: docker-compose.yml
    dest: /opt/npm/docker-compose.yml
    owner: root
    group: root
    mode: '0644'

- name: Lancer Nginx Proxy Manager
  shell: docker compose up -d
  args:
    chdir: /opt/npm