---
- hosts: monitoring
  become: yes
  vars_files:
    - ../vault/secrets.yml
  roles:
    - common
    - uptime-kuma
    - prometheus
    - loki
    - grafana

- hosts: all
  become: yes
  roles:
    - node-exporter
    - promtail
