---
- name: Create app directory
  file:
    path: /opt/snipeit
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Copy docker-compose.yml
  template:
    src: docker-compose.yml.j2
    dest: /opt/snipeit/docker-compose.yml
    owner: root
    group: root
    mode: '0644'

- name: Copy .env file
  template:
    src: .env.j2
    dest: /opt/snipeit/.env
    owner: root
    group: root
    mode: '0644'

- name: Start Snipe-IT
  shell: docker compose up -d
  args:
    chdir: /opt/snipeit
